### ISSUE TITLE
Inconsistent assertion/question handling

### ISSUE THREAD

**Issue by munichbughunter** [testla-project/testla-screenplay-playwright-js#10]
We are inconsistent in our assertion/question handling. 

Actual we have to write this to asks questions / make assertions: 
```javascript
expect(await adminActor.asks(Element.isVisible(dropdownOptionApproval))).toBe(true);
```

To make it more consistent we should write something like that: 
```javascript
// Option 1
await adminActor.asks(Element.isVisible(dropdownOptionApproval, false))
// Option 2
await adminActor.asks(Element.isVisible(dropdownOptionApproval))
// Option 3
await adminActor.asks(Element.not.isVisible(dropdownOptionApproval))
```

**Comment by ngu-oli** [comment]
modified the questions to support Option 3 (Element.not.isVisible(...))

**Comment by kbrueckner** [comment]
Just a quick thought around the not approach. What about

**Comment by munichbughunter** [comment]
How does playwright handle this? We should use the same constellation/ wording
