### ISSUE TITLE
Question: actor fixtures - usage and questions on UseSalesActor 

### ISSUE THREAD

**Issue by InduKrish** [testla-project/testla-screenplay-playwright-js#33]
Fixtures:

```javascript
import { test as base } from '@playwright/test';
import { Actor } from '@testla/screenplay-playwright';
import { SalesActor } from '../screenplay/actors/SalesActor';
type AppActors = {
    salesRepresentative: Actor;
    salesManager: Actor;
};
export const test = base.extend<AppActors>({
    salesRepresentative: async ({ browser }, use) => {
        const context = await browser.newContext();
        const page = await context.newPage();
        const contributor = SalesActor(page, 'James');
        await use(contributor);
    }
});
export { expect } from '@playwright/test';
```

SalesActor usage:
This is a fixture. And looks like that:

```javascript
import { test as base } from '@playwright/test';
import { Actor } from '@testla/screenplay-playwright';
import { UseAPI } from '@testla/screenplay-playwright/api';

type MyActors = {
    salesActor: Actor;
};

export const test = base.extend<MyActors>({
    salesActor: async ({ browser, request }, use) => {
        const context = await browser.newContext();
        const page = await context.newPage();
        const salesActor = UseSalesActor(page, request, 'MyNameOfTheActor', `${process.env.USERNAME}`, `${process.env.PASSWORD}`);
        salesActor.with('page', page);
        
        await use(salesActor);
    },
});

export { expect } from '@playwright/test';
```

**_Questions:_**

1. wondering why we need to call SalesActor(page, 'James') inside salesRepresentative fixture? it is a fixture(salesRepresentative) inside other fixture( salesActor)
2.const contributor = SalesActor(page, 'James');, how SalesActor gets initialized?
3.ok, and what is UseSalesActor please ? wondering why we need that, what do we define inside UseSalesActor please?
const salesActor = UseSalesActor(page, request, 'MyNameOfTheActor', `${process.env.USERNAME}`, `${process.env.PASSWORD}`);
4. where are we passing the application url here to login? can you please clarify.  I am not looking for api requests for now. 

do you have all these examples available in any repository? that will be easy to be refer to

i have used fixtures previously in page object, and screenshot is attached below,  here i am not sure what UseSalesActor is for, can you please help me with an example, so that I can use a similar structure in my project?
**const salesActor = UseSalesActor(page, request, 'MyNameOfTheActor', `${process.env.USERNAME}`, `${process.env.PASSWORD}`);**

Can you please share what is inside UseSalesActor?

<img width="928" alt="Screen Shot 2022-10-06 at 10 36 53 PM (1)" src="https://user-images.githubusercontent.com/113629123/204605485-31cc4b80-4931-4bd3-8119-249ae3a3811e.png">

**Comment by munichbughunter** [comment]
It is clarified.
