### ISSUE TITLE
More readable test steps in Playwright's report

### ISSUE THREAD

**Issue by nopol10** [testla-project/testla-screenplay-playwright-js#34]
This library is really helpful in implementing the Screenplay pattern! However a small issue I have is that the test steps shown in the report show the playwright function call inside the ability instead of the call made in my test file, which makes it slightly more troublesome to trace (see screenshot below).
Do you know if there's a way around this? One workaround I'm thinking of is to wrap my Actions in [`test.step`](https://playwright.dev/docs/api/class-test#test-step) to make it more readable.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/314281/206064939-a2485ecc-7563-44d4-9431-01df3bf997a4.png">

**Comment by munichbughunter** [comment]
What kind of message do you want to print? You can use annotations if you have something per test basis like that:
`js
test.info().annotations.push({ type: 'something', description: 'some description' });
`
Also console.logs should get reflected in the stdout section. For grouping, you can use test steps: https://playwright.dev/docs/api/class-test#test-step

**Comment by kbrueckner** [comment]
SInce quite a while you can activate logging to stdout by setting an env var

```

export DEBUG=testla:sp
```

However working on a proper report. Stay tuned!

**Comment by kbrueckner** [comment]
Beta (1.7.0) is out for this feature
