### ISSUE TITLE
Available Api Questions

### ISSUE THREAD

**Issue by lefado** [testla-project/testla-screenplay-playwright-js#37]
I am trying to use Api Questions which are described in the docs. However, I cannot see any complete example for Api Questions.
For example, I would like to use below question
`await actor.asks(Response.has.statusCode(response, 200))`

My doubt is what should be variable `response`. I have tried below code, but I am getting a TS error `Property 'duration' is missing in type`
```
const response = await (await page.waitForRequest(url => url.url().includes('search?q=scale+old'))).response()
await actor.asks(Response.has.statusCode(response, 200))
```

Can you provide an example which a response for a specific request is checked, please?

Thanks in advance!

**Comment by ngu-oli** [comment]
The `response` variable of the Api Question is of the self-defined type `Response` from our library (note that the type `Response` from Playwright and our self-defined type `Response` are not the same, yes this is a little bit confusing. We are working on a better documentation).

If you want to make use of our Api Questions, it would be best to use our Api Requests as well, as they return a variable of our `Response` type as a result. An example could look like this:

```
const response = await actor.attemptsTo(
    Get.from('https://google.com).withResponseBodyFormat('text'),
);
await actor.asks(Response.has.statusCode(response, 200));
```


If you can't use our Api Requests but still want to use our Api Questions, you will have to convert the Response of your Api Request to our `Response` type. Our `Response` type consists of the following (see https://github.com/testla-project/testla-screenplay-playwright-js/blob/main/src/api/types.ts for reference):

```
/**
 * Response type which is returned from any request
 */
export type Response = {
    body: ResponseBodyType; // export type ResponseBodyType = Buffer | object | string | null;
    status: number;
    headers: Headers;
    duration: number;
};
```
