### ISSUE TITLE
Please reference the original sources to avoid license violation

### ISSUE THREAD

**Issue by jan-molak** [testla-project/testla-screenplay-playwright-js#64]
### What is the issue?

Hi there! It's great to see more developers interested in exploring the [Screenplay Pattern](https://serenity-js.org/handbook/design/screenplay-pattern/) and benefiting from research the [Serenity/JS community](https://github.com/serenity-js) has done in this area over the years.

However, please note that Serenity/JS documentation is [distributed under the Creative Commons BY-NC-SA 4.0 International license](https://serenity-js.org/license/), which states that _you are free to share, copy, and redistribute the material in any medium or format as well as adapt, remix, transform, and build upon the material_, as long as you _give appropriate credit_.

As I'm sure you're aware, the documentation of the [Screenplay Pattern in Testla documentation](https://github.com/testla-project/testla-screenplay-playwright-js/blob/7e71fcc9f648b9471ebdc9ff4f06b51c135aad3a/docs/screenplay_pattern_overview/screenplay_pattern.md) is remarkably similar to my article on the topic published as part of the [Serenity/JS Handbook](https://serenity-js.org/handbook/design/screenplay-pattern/). And so, I'd be grateful if you could honour the [Serenity/JS documentation license](https://serenity-js.org/license/) and add the following opening note to your article:

```
Based on the ["Screenplay Pattern"](https://serenity-js.org/handbook/design/screenplay-pattern/)
from the ["Serenity/JS Handbook"](https://serenity-js.org/handbook/) by Jan Molak.
```

If you'd like to learn more about the Screenplay Pattern, Serenity/JS, or have features in mind that the original framework doesn't offer yet, I'd also like to invite you to become [Serenity/JS contributors](https://serenity-js.org/contributing/) yourselves!

I am happy to answer any questions that you might have.

Kind regards,
Jan Molak

**Comment by munichbughunter** [comment]
Dear @jan-molak ,

Thank you very much for your comment and the ticket. We appreciate your feedback and support. We will take care of the problem as soon as possible and find a solution. 
We apologize for the inconvenience this has caused you. It was an oversight on our part and we will do everything we can to avoid it. 

Best, 
Patrick

**Comment by jan-molak** [comment]
Thanks, @munichbughunter, I appreciate it! Please let me know if you have any questions or want to discuss possible options.

**Comment by munichbughunter** [comment]
@jan-molak can you please take a look at the PR: https://github.com/testla-project/testla-screenplay-playwright-js/pull/70
If you see no license violation I would merge that.

**Comment by munichbughunter** [comment]
Hey @jan-molak, 
based on your LinkedIn Message: 
```text
Hi Patrick! I think the removal of copy-righted content is a very good start, thanks for doing that!
```
we assume that the issue is resolved.

**Comment by jan-molak** [comment]
Thanks for starting to rectify the issues, @munichbughunter!

> we assume that the issue is resolved.

Unfortunately, there are other examples of plagiarism that the "Testla project" exhibits.

For example, note how the documentation of ["testla-screenplay-core-js"](https://github.com/testla-project/testla-screenplay-core-js/blob/f34250c2fb977ac43cb6a69544105e81588ba3e9/README.md#what-is-screenplay-pattern-and-how-does-it-work) copies entire passages from [thie Serenity/JS article](https://serenity-js.org/handbook/getting-started/serenity-js-with-playwright-test/#using-serenityjs-screenplay-pattern-apis).

---

Since Testla is clearly based on Serenity/JS and our work on Screenplay, wouldn't you consider it to be in good tone for Testla to reference prior art? For example, this is how the Cucumber team does it with their [@cucumber/screenplay](https://www.npmjs.com/package/@cucumber/screenplay#credits) implementation.

**Comment by munichbughunter** [comment]
@jan-molak we created a new Issue here: https://github.com/testla-project/testla-screenplay-core-js/issues/10 which adresses your point.

**Comment by munichbughunter** [comment]
@jan-molak the following PR: https://github.com/testla-project/testla-screenplay-core-js/pull/11
should address the points you mentioned. 
Please confirm that both changes are ok for you.

**Comment by jan-molak** [comment]
Thanks @munichbughunter, I'm happy with https://github.com/testla-project/testla-screenplay-core-js/pull/11 addressing https://github.com/testla-project/testla-screenplay-playwright-js/issues/64#issuecomment-1898207711
