### ISSUE TITLE
✨ Allow Playwright Locators to be lazily loaded

### ISSUE THREAD

**Issue by JEnglandOhalo** [testla-project/testla-screenplay-playwright-js#66]
### What are you trying to do?

We would like to be able to use Playwright's [factory methods for creating a Locator from the page](https://playwright.dev/python/docs/api/class-locator#locator-get-by-role) such as `page.getByRole()` with the screenplay pattern.

This could be achieved by allowing the use of `functions` to supply the `Locator` to be interacted with by an `Action`

```ts
static LOGIN_BUTTON: (page: Page) => Locator = (page: Page) => page.getByRole('button', { name: 'Sign in' })
```

Then in the `Task` we can use the standard actions to interact with the selector.

```ts
Click.on(LOGIN_BUTTON)
```

### Why is this important to you?

This would allow for more advanced Playwright selectors to be used with `testla` screenplay in a convenient  fashion

### How are you currently working around this?

We've got a very butchered `PageObject Pattern` attempt but I think that's because we misunderstood some aspects of the `Screenplay Pattern` when we first adopted `Testla`.

Potentially this could be adapted so that the `PageObject` class becomes more like a `Factory Pattern` that produces `Locators` instead.

```js
const loginPage = new LoginPage(BrowseTheWeb.as(actor).page())
await actor.attemptsTo(
  Click.on(loginPage.getLoginButton()),
);
```

**Comment by kbrueckner** [comment]
Hi [JEnglandOhalo](https://github.com/JEnglandOhalo), thanks for the proposal, we will definitely have a look into this.
We actually were already brainstorming on how to support that kind of locator lookup best and you suggestion is valuable input. We will get back to you after discussing that or would even want to invite you to join those discussions if you like.

**Comment by kbrueckner** [comment]
No timing planned yet but we'll let you know in advance with enough buffer to ensure you can join. Will get back to you with detail as soon as I have some.

**Comment by kbrueckner** [comment]
Please feel free to join us on https://discord.gg/Zra4PmtP for further communication on that topic.

**Comment by kbrueckner** [comment]
Can you try this one instead: https://discord.gg/uqFMazSA
