### ISSUE TITLE
No versions avaliable for tesla-screenplay-playwright🐞 <title>

### ISSUE THREAD

**Issue by gicuadrado** [testla-project/testla-screenplay-playwright-js#79]
### What is the issue?

Al instalar la librería tesla segun el comando descrito en la documentación oficial me muestra un erro que no hay versiones disponibles

### Log output

PS C:\Users\CCXC Administrador\Documents\FOLDER 2024\FOLDER 2023\PORVENIR\Automatización\Auth Tesla> npm install --save-dev testla-screenplay-playwright
npm ERR! code ENOVERSIONS
npm ERR! No versions available for testla-screenplay-playwright

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\CCXC Administrador\AppData\Local\npm-cache\_logs\2024-03-19T17_38_29_861Z-debug-0.log

### Testla version

18.16.0

### Browser

Chromium

**Comment by kbrueckner** [comment]
Thanks for reporting the issue. Please keep in mind to report issues in english language.
Also we would need a little more details to investigate that.

The library is currently in version 1.5.0, a version 18.16.0 does not exist - we assume that your node version is 18.16.0?
Can you please forward us the the correct version information of @testla/screenplay, @testla/screenplay-playwright and node from your package.json.

**Comment by achiong22** [comment]
I think here the documentation might be wrong. it should be  npm install --save-dev @testla/screenplay-playwright not npm install --save-dev testla-screenplay-playwright

**Comment by kbrueckner** [comment]
@achiong22 you are absolutely right. That is definitely a documentation mistake. We'll fix that!

**Comment by kbrueckner** [comment]
In the meantime, [gicuadrado](https://github.com/gicuadrado) please be aware of you have to install testla like mentioned by achiong22.

```
npm install --save-dev @testla/screenplay-playwright
```
