### ISSUE TITLE
 BrowseTheWeb to offer access to storages and cookies

### ISSUE THREAD

**Issue by kbrueckner** [testla-project/testla-screenplay-playwright-js#8]
We should add some abstraction layer inside BrowseTheWeb to offer access to
- session storage
- local storage
- cookies
inside the current browser window.

**Comment by ngu-oli** [comment]
added functions:
- getBrowserCookies
- addBrowserCookies
- clearBrowserCookies
- getBrowserStorageState <---- Returns storage state for the browser context, contains current cookies and local storage snapshot.

i didn't find anything for session storage

**Comment by ngu-oli** [comment]
added actions Add, Fetch and Remove to access cookies, session storage and local storage.
